services:
  - type: web
    name: subconnect
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist